"""Контракты событий Realtime Translator (ARCHITECTURE.md раздел 5).

МЕНЯТЬ ТОЛЬКО С РАЗРЕШЕНИЯ ВЛАДЕЛЬЦА ПРОЕКТА (CLAUDE.md, закон 2).
"""

from engine.contracts.events import (
    ALL_TYPES,
    COMMAND_SESSION_START,
    COMMAND_SESSION_STOP,
    EVENT_CLASSES,
    EVENT_METRICS_LATENCY,
    EVENT_SESSION_START,
    EVENT_SESSION_STATE,
    EVENT_SESSION_STOP,
    EVENT_STT_FINAL,
    EVENT_STT_PARTIAL,
    EVENT_TRANSLATION_READY,
    EVENT_TTS_CHUNK,
    ContractError,
    Envelope,
    Event,
    Lang,
    Langs,
    MetricsLatency,
    SessionStart,
    SessionState,
    SessionStatus,
    SessionStop,
    Stream,
    SttFinal,
    SttPartial,
    TranslationReady,
    TtsChunk,
    now_ms,
    parse_event,
    to_json,
    validate_envelope,
)

__all__ = [
    "ALL_TYPES",
    "COMMAND_SESSION_START",
    "COMMAND_SESSION_STOP",
    "EVENT_CLASSES",
    "EVENT_METRICS_LATENCY",
    "EVENT_SESSION_START",
    "EVENT_SESSION_STATE",
    "EVENT_SESSION_STOP",
    "EVENT_STT_FINAL",
    "EVENT_STT_PARTIAL",
    "EVENT_TRANSLATION_READY",
    "EVENT_TTS_CHUNK",
    "ContractError",
    "Envelope",
    "Event",
    "Lang",
    "Langs",
    "MetricsLatency",
    "SessionStart",
    "SessionState",
    "SessionStatus",
    "SessionStop",
    "Stream",
    "SttFinal",
    "SttPartial",
    "TranslationReady",
    "TtsChunk",
    "now_ms",
    "parse_event",
    "to_json",
    "validate_envelope",
]
